# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'detail_vol.ui'
##
## Created by: Qt User Interface Compiler version 6.1.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_Detail_vol(object):
    def setupUi(self, Detail_vol):
        if not Detail_vol.objectName():
            Detail_vol.setObjectName(u"Detail_vol")
        Detail_vol.resize(718, 790)
        self.lb_detail_vol = QLabel(Detail_vol)
        self.lb_detail_vol.setObjectName(u"lb_detail_vol")
        self.lb_detail_vol.setGeometry(QRect(240, 30, 211, 41))
        font = QFont()
        font.setPointSize(22)
        self.lb_detail_vol.setFont(font)
        self.lb_detail_vol_date = QLabel(Detail_vol)
        self.lb_detail_vol_date.setObjectName(u"lb_detail_vol_date")
        self.lb_detail_vol_date.setGeometry(QRect(50, 160, 101, 21))
        font1 = QFont()
        font1.setPointSize(13)
        self.lb_detail_vol_date.setFont(font1)
        self.lb_detail_vol_decollage = QLabel(Detail_vol)
        self.lb_detail_vol_decollage.setObjectName(u"lb_detail_vol_decollage")
        self.lb_detail_vol_decollage.setGeometry(QRect(50, 200, 101, 21))
        self.lb_detail_vol_decollage.setFont(font1)
        self.lb_detail_vol_decollage.setFrameShape(QFrame.NoFrame)
        self.lb_detail_vol_atterrissage = QLabel(Detail_vol)
        self.lb_detail_vol_atterrissage.setObjectName(u"lb_detail_vol_atterrissage")
        self.lb_detail_vol_atterrissage.setGeometry(QRect(50, 240, 101, 21))
        self.lb_detail_vol_atterrissage.setFont(font1)
        self.lb_detail_vol_atterrissage.setFrameShape(QFrame.NoFrame)
        self.lb_detail_vol_distance = QLabel(Detail_vol)
        self.lb_detail_vol_distance.setObjectName(u"lb_detail_vol_distance")
        self.lb_detail_vol_distance.setGeometry(QRect(50, 280, 101, 21))
        self.lb_detail_vol_distance.setFont(font1)
        self.lb_detail_vol_distance_cumulee = QLabel(Detail_vol)
        self.lb_detail_vol_distance_cumulee.setObjectName(u"lb_detail_vol_distance_cumulee")
        self.lb_detail_vol_distance_cumulee.setGeometry(QRect(50, 320, 151, 21))
        self.lb_detail_vol_distance_cumulee.setFont(font1)
        self.lb_detail_vol_voile = QLabel(Detail_vol)
        self.lb_detail_vol_voile.setObjectName(u"lb_detail_vol_voile")
        self.lb_detail_vol_voile.setGeometry(QRect(50, 360, 101, 21))
        self.lb_detail_vol_voile.setFont(font1)
        self.lb_detail_vol_vitesse_max = QLabel(Detail_vol)
        self.lb_detail_vol_vitesse_max.setObjectName(u"lb_detail_vol_vitesse_max")
        self.lb_detail_vol_vitesse_max.setGeometry(QRect(50, 400, 101, 21))
        self.lb_detail_vol_vitesse_max.setFont(font1)
        self.lb_detail_vol_vitesse_moyenne = QLabel(Detail_vol)
        self.lb_detail_vol_vitesse_moyenne.setObjectName(u"lb_detail_vol_vitesse_moyenne")
        self.lb_detail_vol_vitesse_moyenne.setGeometry(QRect(50, 440, 141, 21))
        self.lb_detail_vol_vitesse_moyenne.setFont(font1)
        self.lb_detail_vol_plafond = QLabel(Detail_vol)
        self.lb_detail_vol_plafond.setObjectName(u"lb_detail_vol_plafond")
        self.lb_detail_vol_plafond.setGeometry(QRect(50, 480, 101, 21))
        self.lb_detail_vol_plafond.setFont(font1)
        self.lb_detail_vol_gain = QLabel(Detail_vol)
        self.lb_detail_vol_gain.setObjectName(u"lb_detail_vol_gain")
        self.lb_detail_vol_gain.setGeometry(QRect(50, 520, 101, 21))
        self.lb_detail_vol_gain.setFont(font1)
        self.lb_detail_vol_temps_vol = QLabel(Detail_vol)
        self.lb_detail_vol_temps_vol.setObjectName(u"lb_detail_vol_temps_vol")
        self.lb_detail_vol_temps_vol.setGeometry(QRect(50, 560, 121, 21))
        self.lb_detail_vol_temps_vol.setFont(font1)
        self.lb_detail_vol_vario_max = QLabel(Detail_vol)
        self.lb_detail_vol_vario_max.setObjectName(u"lb_detail_vol_vario_max")
        self.lb_detail_vol_vario_max.setGeometry(QRect(50, 600, 101, 21))
        self.lb_detail_vol_vario_max.setFont(font1)
        self.lb_detail_vol_gmax = QLabel(Detail_vol)
        self.lb_detail_vol_gmax.setObjectName(u"lb_detail_vol_gmax")
        self.lb_detail_vol_gmax.setGeometry(QRect(50, 640, 101, 21))
        self.lb_detail_vol_gmax.setFont(font1)
        self.gb_detail_vol_label = QGroupBox(Detail_vol)
        self.gb_detail_vol_label.setObjectName(u"gb_detail_vol_label")
        self.gb_detail_vol_label.setEnabled(True)
        self.gb_detail_vol_label.setGeometry(QRect(210, 120, 241, 571))
        self.lb_detail_vol_gmax_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_gmax_2.setObjectName(u"lb_detail_vol_gmax_2")
        self.lb_detail_vol_gmax_2.setGeometry(QRect(40, 520, 101, 21))
        self.lb_detail_vol_gmax_2.setFont(font1)
        self.lb_detail_vol_voile_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_voile_2.setObjectName(u"lb_detail_vol_voile_2")
        self.lb_detail_vol_voile_2.setGeometry(QRect(40, 240, 101, 21))
        self.lb_detail_vol_voile_2.setFont(font1)
        self.lb_detail_vol_temps_vol_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_temps_vol_2.setObjectName(u"lb_detail_vol_temps_vol_2")
        self.lb_detail_vol_temps_vol_2.setGeometry(QRect(40, 440, 121, 21))
        self.lb_detail_vol_temps_vol_2.setFont(font1)
        self.lb_detail_vol_decollage_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_decollage_2.setObjectName(u"lb_detail_vol_decollage_2")
        self.lb_detail_vol_decollage_2.setGeometry(QRect(40, 80, 101, 21))
        self.lb_detail_vol_decollage_2.setFont(font1)
        self.lb_detail_vol_decollage_2.setFrameShape(QFrame.NoFrame)
        self.lb_detail_vol_vitesse_max_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_vitesse_max_2.setObjectName(u"lb_detail_vol_vitesse_max_2")
        self.lb_detail_vol_vitesse_max_2.setGeometry(QRect(40, 280, 101, 21))
        self.lb_detail_vol_vitesse_max_2.setFont(font1)
        self.lb_detail_vol_distance_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_distance_2.setObjectName(u"lb_detail_vol_distance_2")
        self.lb_detail_vol_distance_2.setGeometry(QRect(40, 160, 101, 21))
        self.lb_detail_vol_distance_2.setFont(font1)
        self.lb_detail_vol_date_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_date_2.setObjectName(u"lb_detail_vol_date_2")
        self.lb_detail_vol_date_2.setGeometry(QRect(40, 40, 101, 21))
        self.lb_detail_vol_date_2.setFont(font1)
        self.lb_detail_vol_vario_max_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_vario_max_2.setObjectName(u"lb_detail_vol_vario_max_2")
        self.lb_detail_vol_vario_max_2.setGeometry(QRect(40, 480, 101, 21))
        self.lb_detail_vol_vario_max_2.setFont(font1)
        self.lb_detail_vol_plafond_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_plafond_2.setObjectName(u"lb_detail_vol_plafond_2")
        self.lb_detail_vol_plafond_2.setGeometry(QRect(40, 360, 101, 21))
        self.lb_detail_vol_plafond_2.setFont(font1)
        self.lb_detail_vol_vitesse_moyenne_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_vitesse_moyenne_2.setObjectName(u"lb_detail_vol_vitesse_moyenne_2")
        self.lb_detail_vol_vitesse_moyenne_2.setGeometry(QRect(40, 320, 141, 21))
        self.lb_detail_vol_vitesse_moyenne_2.setFont(font1)
        self.lb_detail_vol_gain_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_gain_2.setObjectName(u"lb_detail_vol_gain_2")
        self.lb_detail_vol_gain_2.setGeometry(QRect(40, 400, 101, 21))
        self.lb_detail_vol_gain_2.setFont(font1)
        self.lb_detail_vol_distance_cumulee_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_distance_cumulee_2.setObjectName(u"lb_detail_vol_distance_cumulee_2")
        self.lb_detail_vol_distance_cumulee_2.setGeometry(QRect(40, 200, 151, 21))
        self.lb_detail_vol_distance_cumulee_2.setFont(font1)
        self.lb_detail_vol_atterrissage_2 = QLabel(self.gb_detail_vol_label)
        self.lb_detail_vol_atterrissage_2.setObjectName(u"lb_detail_vol_atterrissage_2")
        self.lb_detail_vol_atterrissage_2.setGeometry(QRect(40, 120, 101, 21))
        self.lb_detail_vol_atterrissage_2.setFont(font1)
        self.lb_detail_vol_atterrissage_2.setFrameShape(QFrame.NoFrame)
        self.gb_detail_vol_le = QGroupBox(Detail_vol)
        self.gb_detail_vol_le.setObjectName(u"gb_detail_vol_le")
        self.gb_detail_vol_le.setGeometry(QRect(470, 120, 221, 571))
        self.le_detail_vol_date = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_date.setObjectName(u"le_detail_vol_date")
        self.le_detail_vol_date.setGeometry(QRect(30, 40, 161, 31))
        self.le_detail_vol_decollage = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_decollage.setObjectName(u"le_detail_vol_decollage")
        self.le_detail_vol_decollage.setGeometry(QRect(30, 80, 161, 31))
        self.le_detail_vol_atterrissage = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_atterrissage.setObjectName(u"le_detail_vol_atterrissage")
        self.le_detail_vol_atterrissage.setGeometry(QRect(30, 120, 161, 31))
        self.le_detail_vol_distance = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_distance.setObjectName(u"le_detail_vol_distance")
        self.le_detail_vol_distance.setGeometry(QRect(30, 160, 161, 31))
        self.le_detail_vol_distance_cumulee = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_distance_cumulee.setObjectName(u"le_detail_vol_distance_cumulee")
        self.le_detail_vol_distance_cumulee.setGeometry(QRect(30, 200, 161, 31))
        self.le_detail_vol_voile = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_voile.setObjectName(u"le_detail_vol_voile")
        self.le_detail_vol_voile.setGeometry(QRect(30, 240, 161, 31))
        self.le_detail_vol_vitesse_max = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_vitesse_max.setObjectName(u"le_detail_vol_vitesse_max")
        self.le_detail_vol_vitesse_max.setGeometry(QRect(30, 280, 161, 31))
        self.le_detail_vol_vitesse_moyenne = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_vitesse_moyenne.setObjectName(u"le_detail_vol_vitesse_moyenne")
        self.le_detail_vol_vitesse_moyenne.setGeometry(QRect(30, 320, 161, 31))
        self.le_detail_vol_plafond = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_plafond.setObjectName(u"le_detail_vol_plafond")
        self.le_detail_vol_plafond.setGeometry(QRect(30, 360, 161, 31))
        self.le_detail_vol_gain = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_gain.setObjectName(u"le_detail_vol_gain")
        self.le_detail_vol_gain.setGeometry(QRect(30, 400, 161, 31))
        self.le_detail_vol_temps_vol = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_temps_vol.setObjectName(u"le_detail_vol_temps_vol")
        self.le_detail_vol_temps_vol.setGeometry(QRect(30, 440, 161, 31))
        self.le_detail_vol_vario_max = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_vario_max.setObjectName(u"le_detail_vol_vario_max")
        self.le_detail_vol_vario_max.setGeometry(QRect(30, 480, 161, 31))
        self.le_detail_vol_gmax = QLineEdit(self.gb_detail_vol_le)
        self.le_detail_vol_gmax.setObjectName(u"le_detail_vol_gmax")
        self.le_detail_vol_gmax.setGeometry(QRect(30, 520, 161, 31))
        self.pb_detail_vol_modifier = QPushButton(Detail_vol)
        self.pb_detail_vol_modifier.setObjectName(u"pb_detail_vol_modifier")
        self.pb_detail_vol_modifier.setGeometry(QRect(140, 710, 141, 51))
        font2 = QFont()
        font2.setPointSize(12)
        self.pb_detail_vol_modifier.setFont(font2)
        self.pb_detail_vol_retour = QPushButton(Detail_vol)
        self.pb_detail_vol_retour.setObjectName(u"pb_detail_vol_retour")
        self.pb_detail_vol_retour.setGeometry(QRect(310, 710, 141, 51))
        self.pb_detail_vol_retour.setFont(font2)
        self.pb_detail_vol_valider = QPushButton(Detail_vol)
        self.pb_detail_vol_valider.setObjectName(u"pb_detail_vol_valider")
        self.pb_detail_vol_valider.setGeometry(QRect(490, 710, 141, 51))
        self.pb_detail_vol_valider.setFont(font2)

        self.retranslateUi(Detail_vol)

        QMetaObject.connectSlotsByName(Detail_vol)
    # setupUi

    def retranslateUi(self, Detail_vol):
        Detail_vol.setWindowTitle(QCoreApplication.translate("Detail_vol", u"Form", None))
        self.lb_detail_vol.setText(QCoreApplication.translate("Detail_vol", u"D\u00e9tail du vol :", None))
        self.lb_detail_vol_date.setText(QCoreApplication.translate("Detail_vol", u"Date :", None))
        self.lb_detail_vol_decollage.setText(QCoreApplication.translate("Detail_vol", u"D\u00e9collage :", None))
        self.lb_detail_vol_atterrissage.setText(QCoreApplication.translate("Detail_vol", u"Atterrissage :", None))
        self.lb_detail_vol_distance.setText(QCoreApplication.translate("Detail_vol", u"Distance :", None))
        self.lb_detail_vol_distance_cumulee.setText(QCoreApplication.translate("Detail_vol", u"Distance cumul\u00e9e :", None))
        self.lb_detail_vol_voile.setText(QCoreApplication.translate("Detail_vol", u"Voile :", None))
        self.lb_detail_vol_vitesse_max.setText(QCoreApplication.translate("Detail_vol", u"Vitesse max :", None))
        self.lb_detail_vol_vitesse_moyenne.setText(QCoreApplication.translate("Detail_vol", u"Vitesse moyenne :", None))
        self.lb_detail_vol_plafond.setText(QCoreApplication.translate("Detail_vol", u"Plafond :", None))
        self.lb_detail_vol_gain.setText(QCoreApplication.translate("Detail_vol", u"Gain :", None))
        self.lb_detail_vol_temps_vol.setText(QCoreApplication.translate("Detail_vol", u"Dur\u00e9e du vol :", None))
        self.lb_detail_vol_vario_max.setText(QCoreApplication.translate("Detail_vol", u"Vario max :", None))
        self.lb_detail_vol_gmax.setText(QCoreApplication.translate("Detail_vol", u"G max :", None))
        self.gb_detail_vol_label.setTitle(QCoreApplication.translate("Detail_vol", u"Le vol :", None))
        self.lb_detail_vol_gmax_2.setText(QCoreApplication.translate("Detail_vol", u"G max :", None))
        self.lb_detail_vol_voile_2.setText(QCoreApplication.translate("Detail_vol", u"Voile :", None))
        self.lb_detail_vol_temps_vol_2.setText(QCoreApplication.translate("Detail_vol", u"Dur\u00e9e du vol :", None))
        self.lb_detail_vol_decollage_2.setText(QCoreApplication.translate("Detail_vol", u"D\u00e9collage :", None))
        self.lb_detail_vol_vitesse_max_2.setText(QCoreApplication.translate("Detail_vol", u"Vitesse max :", None))
        self.lb_detail_vol_distance_2.setText(QCoreApplication.translate("Detail_vol", u"Distance :", None))
        self.lb_detail_vol_date_2.setText(QCoreApplication.translate("Detail_vol", u"Date :", None))
        self.lb_detail_vol_vario_max_2.setText(QCoreApplication.translate("Detail_vol", u"Vario max :", None))
        self.lb_detail_vol_plafond_2.setText(QCoreApplication.translate("Detail_vol", u"Plafond :", None))
        self.lb_detail_vol_vitesse_moyenne_2.setText(QCoreApplication.translate("Detail_vol", u"Vitesse moyenne :", None))
        self.lb_detail_vol_gain_2.setText(QCoreApplication.translate("Detail_vol", u"Gain :", None))
        self.lb_detail_vol_distance_cumulee_2.setText(QCoreApplication.translate("Detail_vol", u"Distance cumul\u00e9e :", None))
        self.lb_detail_vol_atterrissage_2.setText(QCoreApplication.translate("Detail_vol", u"Atterrissage :", None))
        self.gb_detail_vol_le.setTitle(QCoreApplication.translate("Detail_vol", u"Le vol :", None))
        self.pb_detail_vol_modifier.setText(QCoreApplication.translate("Detail_vol", u"Modifier", None))
        self.pb_detail_vol_retour.setText(QCoreApplication.translate("Detail_vol", u"Retour", None))
        self.pb_detail_vol_valider.setText(QCoreApplication.translate("Detail_vol", u"Valider", None))
    # retranslateUi

